# Use the official Microsoft Dev Container image for Node.js as a base
FROM mcr.microsoft.com/devcontainers/javascript-node:1-20-bullseye

# You can add other dependencies here if needed.
# For example:
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#    && apt-get -y install --no-install-recommends <your-package-here>