version: '3.8'

services:
  # Your Node.js application service
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Forward ports
    ports:
      - "3000:3000"
      - "5000:5000"

    # Depend on the MongoDB service
    depends_on:
      - mongo

  # MongoDB service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27011" # This can be 27017:27017, but I'll use a different host port to avoid conflicts
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: